Updated to new API in the java code, updated the crud to the JCatapult APIs, removed bad tests, hooked it all up YO

diff --git a/jcatapult-scaffolder/trunk/src/script/main/scaffold b/jcatapult-scaffolder/trunk/src/script/main/scaffold
--- a/jcatapult-scaffolder/trunk/src/script/main/scaffold
+++ b/jcatapult-scaffolder/trunk/src/script/main/scaffold
@@ -1,7 +1,11 @@
 #!/bin/bash
 
 # Run ant jar first
-ant jar
+echo "Running the Ant build"
+if ! ant jar > /dev/null 2>&1; then
+  echo "Build failed"
+  exit 1
+fi
 
 # Build up the scaffolding classpath
 dir=$(dirname $0)
